version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:3.9.14-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
        #      - ./rabbitmq/log/:/var/log/rabbitmq/

volumes:
  rabbitmq:
