version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=gapo_cms
      - MYSQL_ROOT_PASSWORD=gapo_api
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
        #- ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
